myRental_root/books/urls.py
from django.urls import path
from .views import BooksList, AddBookView, UpdateBookView, DeleteBookView

app_name = 'books'

urlpatterns = [
    path('', BooksList.as_view(), name='books-list'),
    path('add-book/', AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>', UpdateBookView.as_view(), name='update-book'),
    path('delete-book/<int:pk>', DeleteBookView.as_view(), name='delete-book'),
    ]

myRental_root/myRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from .api import router

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tfa/', include(tf_urls)),
    path('', RedirectView.as_view(url='/books/'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('accounts/profile-update/', views.UpdateUserProfileView.as_view(), name='update-profile'),
    path('books/', include('books.urls')),
    path('rental/', include('rental.urls')),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken')),
]

myRental_root/templates/partials/_alerts.html
{% load static%}

{% if messages %}
{% for message in messages %}
<div id="message" class="container">
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Zamknij"><span aria-hiden="true">&times;</span>
    </button>
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      Uwaga:
      {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}


{% if form.non_field_errors %}
<div id="error" class="container">
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Zamknij"><span aria-hiden="true">&times;</span>
    </button>
    <strong>UWAGA!</strong>
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
  </div>
</div>
{% endif %}

myRental_root/templates/partials/_menu.html
{% load static%}

{% if user.is_authenticated %}
<div id="menu">
  <ul class="nav container">
    <li class="nav-item">
      <a {% if '/books/' == request.path %}
      class="nav-link active"
      {% else %}
      class="nav-link"
      {% endif %}
      href="{% url 'books:books-list' %}">Lista książek</a></li>
    <li class="nav-item">
      <a {% if 'books/add-book/' == request.path %}
      class="nav-link active"
      {% else %}
      class="nav-link"
      {% endif %}
      href="{% url 'books:add-book' %}">Dodaj książkę</a></li>
  </ul>
</div>
{% endif%}

myRental_root/templates/partials/_navbar.html
{% load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a
            {% if '/accounts/profile/' == request.path %}
          class="nav-link active"
          {% else %}
          class="nav-link"
          {% endif %}
          href="{% url 'user-profile' %}">Profil</a></li>
        <li class="nav-item">
          <a
            {% if '/accounts/logout/' == request.path %}
          class="nav-link active"
          {% else %}
          class="nav-link"
          {% endif %}
          href="{% url 'account_logout' %}">Wyloguj</a></li>
        {% else %}
        <li class="nav-item">
          <a
            {% if '/accounts/login/' == request.path %}
          class="nav-link active"
          {% else %}
          class="nav-link"
          {% endif %}
          href="{% url 'two_factor:profile' %}">Zaloguj</a></li>
        <li class="nav-item">
          <a
            {% if '/accounts/signup/' == request.path %}
          class="nav-link active"
          {% else %}
          class="nav-link"
          {% endif %}
          href="{% url 'account_signup' %}">Utwórz konto</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>