myRental_root/books/urls.py
from django.urls import path
from .views import BooksList, AddBookView, UpdateBookView, DeleteBookView

app_name = 'books'

urlpatterns = [
    path('', BooksList.as_view(), name='books-list'),
    path('add-book/', AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>', UpdateBookView.as_view(), name='update-book'),
    path('delete-book/<int:pk>', DeleteBookView.as_view(), name='delete-book'),
    ]

myRental_root/myRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from .api import router

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tfa/', include(tf_urls)),
    path('', RedirectView.as_view(url='/books/'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('accounts/profile-update/', views.UpdateUserProfileView.as_view(), name='update-profile'),
    path('books/', include('books.urls')),
    path('rental/', include('rental.urls')),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken')),
]

myRental_root/users/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return f'Profile: {self.user.username}'

myRental_root/users/forms.py
from django import forms
from users.models import UserProfile


class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

myRental_root/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import UpdateView

from users.forms import UpdateUserProfileForm
from .models import UserProfile

# Create your views here.
@method_decorator(login_required, name='dispatch')
class UserProfileView(View):
    model = UserProfile
    template_name = 'users/profile.html'

    def get(self, request, *args, **kwargs):
        user_detail = self.model.objects.filter(user = request.user)
        context = {'user_profile' : user_detail}
        return render(request, self.template_name, context = context)

@method_decorator(login_required, name='dispatch')
class UpdateUserProfileView(UpdateView):
    model = UserProfile
    form_class = UpdateUserProfileForm
    template_name_suffix = '_update'

    def get_object(self):
        obj = self.model.objects.get(pk = self.request.user.pk)
        return obj

    def get_success_url(self):
        return reverse('user-profile')

myRental_root/templates/users/profile.html
{% extends "base.html" %}

{% block head_title %}Profil użytkownika{% endblock %}

{% block content %}
<div class="container-fluid" id="profile-page">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Twoje dane</h3>
                {% for user in user_profile %}
                <p>Login: <strong>{{user.user}}</strong></p>
                    <p>E-mail: <strong>{{user.user.email}}</strong></p>
                    <p>Imię: <strong>{{user.first_name}}</strong></p>
                    <p>Nazwisko: <strong>{{user.last_name}}</strong></p>
                {% endfor %}
                <p><a class="btn btn-primary" href="{% url 'update-profile' %}">Edytuj dane</a></p>
                <p><a class="btn btn-primary" href="{% url 'two_factor:profile' %}">Autoryzacja dwuetapowa</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myRental_root/templates/users/userprofile_update.html
{% extends "base.html" %}

{% block head_title %}Edytuj profil{% endblock %}

{% block content %}
<div class="container-fluid" id="profile-page">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Aktualizuj dane</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                    <label for="id_first_name">Imię</label>
                    {{form.first_name}}
                  </div>
                    <div class="form-group">
                    <label for="id_last_name">Nazwisko</label>
                    {{form.last_name}}
                  </div>
                  <a href="{% url 'user-profile' %}">Anuluj</a> <button type="submit" class="btn btn-primary">Aktualizuj</button>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}