myRental_root/books/urls.py
from django.urls import path
from .views import BooksList, AddBookView, UpdateBookView, DeleteBookView

app_name = 'books'

urlpatterns = [
    path('', BooksList.as_view(), name='books-list'),
    path('add-book/', AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>', UpdateBookView.as_view(), name='update-book'),
    path('delete-book/<int:pk>', DeleteBookView.as_view(), name='delete-book'),
    ]

myRental_root/myRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from .api import router

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tfa/', include(tf_urls)),
    path('', RedirectView.as_view(url='/books/'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('accounts/profile-update/', views.UpdateUserProfileView.as_view(), name='update-profile'),
    path('books/', include('books.urls')),
    path('rental/', include('rental.urls')),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken')),
]

myRental_root/rental/urls.py
from django.urls import path
from .views import LoanBookView, ReturnBookView, BookNotAvailable

app_name = 'rental'

urlpatterns = [
    path('loan-book/<int:pk>/', LoanBookView.as_view(), name='loan-book'),
    path('return-book/<int:pk>/', ReturnBookView.as_view(), name='return-book'),
    path('book-not-available/<int:pk>/', BookNotAvailable.as_view(), name='book-not-available'),
    ]

myRental_root/books/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Books(models.Model):
    title = models.CharField(verbose_name='Tytuł', max_length=200)
    author = models.CharField(verbose_name='Autor', max_length=200)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return f'Book: {self.title}, Author: {self.author}'

    class Meta:
        unique_together = ('title', 'author', 'owner',)
        verbose_name_plural = "Książki"
        verbose_name = "Książka"

myRental_root/books/forms.py
from django import forms
from django.core.exceptions import ValidationError

from books.models import Books


class AddBookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['author'].widget.attrs.update({'class': 'form-control'})
        self.fields['title'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Books
        exclude = ['owner', 'status']

    def clean(self):
        cleaned_data = self.cleaned_data
        if Books.objects.filter(title=cleaned_data['title'],
                                author=cleaned_data['author'],
                                owner = self.request.user).exists():
            raise ValidationError('Książka już istnieje')

        return cleaned_data


class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['title', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
        }

myRental_root/books/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import FormView, View, UpdateView, DeleteView
from django.views.generic.base import ContextMixin

from .models import Books
from rental.models import LoanBook
from .forms import AddBookForm, UpdateBookForm


# Create your views here.
@method_decorator(login_required, name='dispatch')
class BooksList(View):
    template_name = 'books/books.html'
    model = Books

    def get(self, request, *args, **kwargs):
        user_books = self.model.objects.filter(owner = request.user).order_by('title')
        page = request.GET.get('page', 1)

        paginator = Paginator(user_books, 10)

        try:
            user_books = paginator.page(page)
        except PageNotAnInteger:
            user_books = paginator.page(1)
        except EmptyPage:
            user_books = paginator.page(paginator.num_pages)

        context = {
            'user_books' : user_books,
        }
        return render(request, self.template_name, context)

@method_decorator(login_required, name='dispatch')
class AddBookView(FormView):
    template_name = 'books/add_book.html'
    form_class = AddBookForm
    success_url = '/books'

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['request'] = self.request
        return kw

    def form_valid(self, form):
        form = form.save(commit=False)
        form.owner = self.request.user
        form.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class UpdateBookView(UpdateView):
    model = Books
    template_name = 'books/update_book.html'
    form_class = UpdateBookForm

    def get_success_url(self):
        return reverse('books:books-list')


@method_decorator(login_required, name='dispatch')
class DeleteBookView(DeleteView):
    model = Books
    template_name = 'books/confirm_delete.html'
    context_object_name = 'delete_book'
    success_url = '/books'

myRental_root/templates/books/add_book.html
{% extends 'base.html' %}

{% block head_title %}Dodaj książkę{% endblock %}

{% block content %}
<div class="container" id="add-books">
  <h1>Dodaj książkę</h1>
  <form method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_author">Autor</label>
      {{ form.author }}
    </div>
    <div class="form-group">
      <label for="id_title">Tytuł książki</label>
      {{form.title}}
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
  </form>
</div>
{% endblock %}

myRental_root/templates/books/books.html
{% extends 'base.html' %}

{% block head_title %}Moje książki{% endblock %}

{% block content %}
<div class="container" id="books">
  <h1>Moje książki</h1>
  {% if user_books %}
  <table class="table">
    <th>Tytuł książki</th>
    <th>Autor</th>
    <th></th>
    <th>Status</th>
    <th></th>
    <th></th>

    {% for book in user_books %}
    <tr>
      <td>{{ book.title }}</td>
      <td>{{ book.author }}</td>
      <td>
        <a href="{% url 'books:update-book' pk=book.pk %}" title="Edytuj książkę"><i class="far fa-edit"></i></a>
        <a href="{% url 'books:delete-book' pk=book.pk %}" title="Usuń książkę"><i class="far fa-trash-alt"></i></a>
      </td>
      <td>{% if book.loanbook %}
            Wypożyczona
          {% else %}
            Dostępna
          {% endif %}
      </td>
      <td>{% if not book.loanbook %}
          <a class="btn btn-success btn-sm" href="{% url 'rental:loan-book' pk=book.pk %}">Wypożycz</a>
          {% else %}
          <a class="btn btn-warning btn-sm" href="{% url 'rental:return-book' pk=book.pk %}">Zwróć</a>
          {% endif %}
      </td>
      <td>
        {% if book.loanbook %}
        <p>Wypożyczona: {{book.loanbook.date}}</br>
          <strong>{{book.loanbook.friend_name}} {{book.loanbook.friend_surname}}</strong> (e-mail: {{book.loanbook.friend_email}})</p>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>Nie masz jeszcze książek na swojej liście. Możesz je dodać <a href="{% url 'books:add-book' %}">tutaj</a>.</p>
  {% endif %}

  {% if user_books.has_other_pages %}
  <ul class="pagination">
    {% if user_books.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ user_books.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in user_books.paginator.page_range %}
    {% if user_books.number == i %}
    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if user_books.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ user_books.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
</div>
{% endblock %}

myRental_root/templates/books/confirm_delete.html
{% extends 'base.html' %}

{% block head_title %}Usuń książkę{% endblock %}

{% block content %}
<div class="container" id="confirm-delete">
  <h1>Usunięcie książki</h1>
  <form method="post">
    {% csrf_token %}
    <p>Czy na pewno chcesz usunąć książkę: <strong>{{ delete_book.title }}</strong>?</p>
    <a href="{% url 'books:books-list' %}">Anuluj</a>
    <button type="submit" class="btn btn-primary">Potwierdź</button>
  </form>
</div>

{% endblock %}

myRental_root/templates/books/update_book.html
{% extends 'base.html' %}

{% block head_title %}Dodaj książkę{% endblock %}

{% block content %}
<div class="container" id="update-book">
  <h1>Aktualizuj książkę</h1>
  <form method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_author">Autor</label>
      {{ form.author }}
    </div>
    <div class="form-group">
      <label for="id_title">Tytuł książki</label>
      {{form.title}}
    </div>
    <a href="{% url 'books:books-list' %}" class="pull-right btn btn-link">Anuluj</a>
    <button type="submit" class="btn btn-primary">Zapisz</button>
  </form>
</div>

{% endblock %}