myRental_root/books/urls.py
from django.urls import path
from .views import BooksList, AddBookView, UpdateBookView, DeleteBookView

app_name = 'books'

urlpatterns = [
    path('', BooksList.as_view(), name='books-list'),
    path('add-book/', AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>', UpdateBookView.as_view(), name='update-book'),
    path('delete-book/<int:pk>', DeleteBookView.as_view(), name='delete-book'),
    ]

myRental_root/myRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from .api import router

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tfa/', include(tf_urls)),
    path('', RedirectView.as_view(url='/books/'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('accounts/profile-update/', views.UpdateUserProfileView.as_view(), name='update-profile'),
    path('books/', include('books.urls')),
    path('rental/', include('rental.urls')),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken')),
]

myRental_root/rental/urls.py
from django.urls import path
from .views import LoanBookView, ReturnBookView, BookNotAvailable

app_name = 'rental'

urlpatterns = [
    path('loan-book/<int:pk>/', LoanBookView.as_view(), name='loan-book'),
    path('return-book/<int:pk>/', ReturnBookView.as_view(), name='return-book'),
    path('book-not-available/<int:pk>/', BookNotAvailable.as_view(), name='book-not-available'),
    ]

myRental_root/rental/models.py
from django.db import models
from books.models import Books

# Create your models here.
class LoanBook(models.Model):
    book = models.OneToOneField(Books, on_delete=models.CASCADE)
    date = models.DateField(verbose_name='Data wypożyczenia')
    friend_name = models.CharField(verbose_name='Imię', max_length=50)
    friend_surname = models.CharField(verbose_name='Nazwisko', max_length=50)
    friend_email = models.EmailField(verbose_name='Adres e-mail')

    def __str__(self):
        return f'{self.book.title} - {self.friend_email} ({self.date})'

    class Meta:
        verbose_name_plural = "Wypożyczenia książek"
        verbose_name = "Wypożyczone książki"

myRental_root/rental/forms.py
from django import forms
from rental.models import LoanBook


class LoanBookForm(forms.ModelForm):

    class Meta:
        model = LoanBook
        fields = ('date', 'friend_name', 'friend_surname', 'friend_email')

        widgets = {'date': forms.DateInput(format=('%d-%m-%Y'),attrs={'class': 'form-control', 'type':'date'}),
                   'friend_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'friend_surname': forms.TextInput(attrs={'class': 'form-control'}),
                   'friend_email': forms.EmailInput(attrs={'class': 'form-control'})
                   }

myRental_root/rental/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import FormView, DeleteView, TemplateView
from .forms import LoanBookForm
from books.models import Books
from .models import LoanBook


# Create your views here.
@method_decorator(login_required, name='dispatch')
class BookNotAvailable(TemplateView):
    template_name = 'rental/book_not_available.html'


@method_decorator(login_required, name='dispatch')
class LoanBookView(FormView):
    template_name = 'rental/loan_book.html'
    form_class = LoanBookForm
    success_url = '/books'

    def dispatch(self, request, *args, **kwargs):
        if LoanBook.objects.filter(book_id=self.kwargs.get('pk')).exists():
            return redirect(reverse('rental:book-not-available', kwargs={'pk':self.kwargs.get('pk')}))
        else:
            return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Books.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        form = form.save(commit=False)
        context = self.get_context_data()
        form.book = context['book']
        context['book'].save()
        form.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ReturnBookView(DeleteView):
    model = LoanBook
    template_name = 'rental/confirm_return.html'
    context_object_name = 'return'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        loan_book_object = LoanBook.objects.get(book_id = pk)
        return loan_book_object

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        book = Books.objects.get(pk=self.kwargs.get('pk'))
        book.status = 'AV'
        book.save()
        return redirect(reverse('books:books-list'))

myRental_root/templates/rental/book_not_available.html
{% extends 'base.html' %}

{% block head_title %}Książka jest niedostępna{% endblock %}

{% block content %}
<div class="container-fluid" id="no-book">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Książka jest niedostępna :(</h3>
              <p>Nie możesz wypożyczyć książki, jeżeli nie została jeszcze zwrócona. <br>Sprawdź jej status
                <a href="{% url 'books:books-list' %}">tutaj</a>.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myRental_root/templates/rental/confirm_return.html
{% extends 'base.html' %}

{% block head_title %}Potwierdź zwrot książki{% endblock %}

{% block content %}
<div class="container" id="confirm-return">
  <h1>Zwrot książki</h1>
  <form method="post">
    {% csrf_token %}
    <p>Czy na pewno chcesz zwrócić książkę: <strong>{{ return.book.title }}</strong>, wypożyczoną przez <strong>{{return.friend_name}}
      {{return.friend_surname}}</strong>?</p>
    <a href="{% url 'books:books-list' %}">Anuluj</a>
    <button type="submit" class="btn btn-primary">Potwierdź</button>
  </form>
</div>
{% endblock %}

myRental_root/templates/rental/loan_book.html
{% extends 'base.html' %}

{% block head_title %}Wypożycz książkę{% endblock %}

{% block content %}
<div class="container" id="loan-book">
  <h1>Wypożycz książkę {{ context.book }}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_date">Data wypożyczenia</label>
      {{ form.date }}
    </div>
    <br>
    <p><strong>Dane wypożyczającego</strong></p>
    <div class="form-group">
      <label for="id_friend_name">Imię</label>
      {{form.friend_name}}
    </div>
    <div class="form-group">
      <label for="id_firend_surname">Nazwisko</label>
      {{form.friend_surname}}
    </div>
    <div class="form-group">
      <label for="id_friend_email">Adres email</label>
      {{form.friend_email}}
    </div>
    <button type="submit" class="btn btn-primary">Wypożycz</button>
  </form>
</div>
{% endblock %}